In [ ]:
#
# hw7pr1:  flower clasification via nearest neighbors
#

In [1]:
# libraries!
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [2]:
# let's read in our flower data...
# 
# for read_csv, use header=0 when row 0 is a header row
# 
filename = 'iris4.csv'
df = pd.read_csv(filename, header=0)   # read the file w/header row #0
print(f"{filename} : file read!")

iris4.csv : file read!


In [4]:
x = 42
print(" x is", x)
print()
print(f" x is |{x: 42d}|")

 x is 42

 x is |                                        42|


In [3]:
#
# let's convert our data to a numpy array, named A
#
A = df.values
print(A)

[[5.7 2.8 4.1 1.3 'unknown']
 [6.3 3.3 6.0 2.5 'unknown']
 [6.2 2.9 4.3 1.3 'unknown']
 [5.1 2.5 3.0 1.1 'unknown']
 [5.4 3.4 1.5 0.4 'unknown']
 [5.2 4.1 1.5 0.1 'unknown']
 [5.8 2.7 5.1 1.9 'unknown']
 [5.7 2.9 4.2 1.3 'unknown']
 [4.8 3.1 1.6 0.2 'unknown']
 [5.1 3.5 1.4 0.2 'setosa']
 [4.9 3.0 1.4 0.2 'setosa']
 [4.7 3.2 1.3 0.2 'setosa']
 [4.6 3.1 1.5 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']
 [5.4 3.9 1.7 0.4 'setosa']
 [4.6 3.4 1.4 0.3 'setosa']
 [5.0 3.4 1.5 0.2 'setosa']
 [4.4 2.9 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.4 3.7 1.5 0.2 'setosa']
 [4.8 3.4 1.6 0.2 'setosa']
 [4.8 3.0 1.4 0.1 'setosa']
 [4.3 3.0 1.1 0.1 'setosa']
 [5.8 4.0 1.2 0.2 'setosa']
 [5.7 4.4 1.5 0.4 'setosa']
 [5.4 3.9 1.3 0.4 'setosa']
 [5.1 3.5 1.4 0.3 'setosa']
 [5.7 3.8 1.7 0.3 'setosa']
 [5.1 3.8 1.5 0.3 'setosa']
 [5.4 3.4 1.7 0.2 'setosa']
 [5.1 3.7 1.5 0.4 'setosa']
 [4.6 3.6 1.0 0.2 'setosa']
 [5.1 3.3 1.7 0.5 'setosa']
 [4.8 3.4 1.9 0.2 'setosa']
 [5.0 3.0 1.6 0.2 'setosa']
 [5.0 3.4 1

In [5]:
# column order is captured in these two "Python dictionaries":

COLS = {              # also: FEATURES
    'sepallen':0,
    'sepalwid':1,
    'petallen':2,
    'petalwid':3,
    'irisname':4,
}
# test this
print("Test COLS:  COLS['petallen'] is", COLS['petallen'])

COL_NAMES = {
    0:'sepallen',
    1:'sepalwid',
    2:'petallen',
    3:'petalwid',
    4:'irisname',
}
print()
print("Test COL_NAMES:   COL_NAMES[3] is", COL_NAMES[3])

Test COLS:  COLS['petallen'] is 2

Test COL_NAMES:   COL_NAMES[3] is petalwid


In [6]:
# let's use the dictionary!
first_flower = A[0]
print("first_flower is", first_flower)
print()
print("Its petalwid is ", first_flower[COLS['petalwid']])
print()
print("Simpler to type: ", first_flower[3])

first_flower is [5.7 2.8 4.1 1.3 'unknown']

Its petalwid is  1.3

Simpler to type:  1.3


In [7]:
# all of the scikit-learn ML routines need numbers, not strings
#
# we will convert flower-species to numbers - first, defining these dictionaries:

SPECIES_NUMS = {
    'setosa':0,
    'versicolor':1,
    'virginica':2,
    'unknown':-1,   
}
# test this
print("Test SPECIES_NUMS:  SPECIES_NUMS['setosa'] is", SPECIES_NUMS['setosa'])

NUM_TO_SPECIES = {
    0:'setosa',
    1:'versicolor',
    2:'virginica',
    -1:'unknown',    # Note: they don't need to be in order!
}
print()
print("Test NUM_TO_SPECIES:   NUM_TO_SPECIES[0] is", NUM_TO_SPECIES[0])

Test SPECIES_NUMS:  SPECIES_NUMS['setosa'] is 0

Test NUM_TO_SPECIES:   NUM_TO_SPECIES[0] is setosa


In [9]:
#
# let's loop through the data (A) and convert the species to numbers
#

NUM_ROWS, NUM_COLS = A.shape

for r in range(NUM_ROWS):
    species = A[r][4]                     # or A[r][  COLS['irisname']  ]
    print(species)
    if type(species) != type('str'): continue   # not a string, keep looping!
        
    species_number = SPECIES_NUMS[species]
    A[r][4] = species_number      # convert to species
    print(A[r])
    
#
# make sure everything is a floating-point value!
#

A = A.astype('float64')  # float64 is the most usual floating-point value...
print("A is an array of type", A.dtype, "and shape", A.shape)
#print(A)

-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
A is an array of type float64 and shape (150, 5)


In [10]:
print("+++ Start of data definitions +++\n")

X_all = A[:,0:4]  # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,4]    # y (labels) ... is all rows, column 4 only

print("X_all is", X_all)
print("y_all is", y_all)

+++ Start of data definitions +++

X_all is [[5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [5.7 2.9 4.2 1.3]
 [4.8 3.1 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 

In [18]:
#
# break our dataset into distinct pieces:   unknown vs labeled
#

NUM_UNKNOWN = 9

X_unknown = X_all[:NUM_UNKNOWN,:]  # unknown up to here...
y_unknown = y_all[:NUM_UNKNOWN]    # unknown up to here...

# known data w/ labels
X_labeled_orig = X_all[NUM_UNKNOWN:,:]  # labeled data starts at this index
y_labeled_orig = y_all[NUM_UNKNOWN:]    # labeled data starts at this index

#
# we scramble the data - but _only_ the labeled data!
# 
indices = np.random.permutation(len(y_labeled_orig))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_labeled = X_labeled_orig[indices]              # we must apply the _same_ permutation to each!
y_labeled = y_labeled_orig[indices]              # again...

In [19]:
print(y_labeled)

[2. 1. 2. 2. 1. 2. 1. 0. 1. 2. 1. 2. 0. 2. 1. 2. 2. 2. 2. 1. 0. 2. 1. 2.
 1. 0. 2. 0. 0. 0. 0. 2. 2. 2. 1. 0. 2. 0. 1. 1. 1. 0. 0. 1. 1. 2. 2. 0.
 2. 1. 0. 0. 1. 1. 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0.
 2. 0. 2. 0. 1. 2. 2. 2. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 2. 0. 2. 0. 2.
 0. 1. 2. 0. 2. 2. 2. 1. 2. 1. 0. 2. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 2. 0.
 2. 0. 2. 0. 2. 2. 1. 0. 0. 1. 0. 2. 2. 0. 2. 0. 2. 0. 2. 1. 0.]


In [20]:
#
# we can re-weight different features here...
#

COL_WEIGHT = {              # also: FEATURE_WEIGHT  compare:  COLS
    'sepallen':1.0,
    'sepalwid':1.0,
    'petallen':1.0,
    'petalwid':1.0,
}

for col_name in COL_WEIGHT:
    i = COLS[col_name]    # get the column index, i, of the col_name
    weight = COL_WEIGHT[col_name]
    print("Weighting", col_name, "by", weight)   # weighting == "multiplying"
    
    X_labeled[:,i] *= weight      # multiply by the weight to give this column ("feature")


Weighting sepallen by 1.0
Weighting sepalwid by 1.0
Weighting petallen by 1.0
Weighting petalwid by 1.0


In [21]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ train on the testing data.
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# most common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_labeled.shape[0]     # the number of labeled rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_labeled[:TEST_SIZE]    # first section are for testing
y_test = y_labeled[:TEST_SIZE]

X_train = X_labeled[TEST_SIZE:]   # all the rest are for training
y_train = y_labeled[TEST_SIZE:]

print("testing with", TEST_SIZE, "rows; training with", (NUM_ROWS-TEST_SIZE), "rows")

testing with 28 rows; training with 113 rows


In [22]:
# +++ This is the "Model-building and -training Cell"
#       
# Create a kNN model and train it! 

from sklearn.neighbors import KNeighborsClassifier

k = 71   # we don't know what k to use, so we guess!  (71 will _not_ be a good value)
knn_model = KNeighborsClassifier(n_neighbors=k)   # here, k is the "k" in kNN

# we train the model (one line!)
knn_model.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a knn classifier with k =", k)  


Created and trained a knn classifier with k = 71


In [23]:
# +++ This is the "Model-testing Cell"
#
# Now, let's see how well we did on our "held-out data" (the testing data)

# Now, run our test set!
predicted_labels = knn_model.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)


Predicted labels: [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 0.]
Actual labels: [2. 1. 2. 2. 1. 2. 1. 0. 1. 2. 1. 2. 0. 2. 1. 2. 2. 2. 2. 1. 0. 2. 1. 2.
 1. 0. 2. 0.]


In [24]:
#
# Let's print these more helpfully, in a vertical table
#

def compare_labels(predicted_labels, actual_labels):
    """ a nicer comparison, including counting how many are correct """
    NUM_LABELS = predicted_labels.shape[0]
    num_correct = 0
    
    for i in range(NUM_LABELS):
        p = predicted_labels[i]
        a = actual_labels[i]
        p_label = NUM_TO_SPECIES[p]
        a_label = NUM_TO_SPECIES[a]
        if p == a:
            toshow = ""
            num_correct += 1
        else:
            toshow = "incorrect"
            
        print(f"row {i}    |  {p}  {a}  |   {p_label} {a_label}   {toshow}")   # cool! "f-string" printing
        
        # even spiffier "formatted printing"  (cool stuff!)  
        #print(f"row {i:2d}    |  {p:1.0f}  {a:1.0f}  |   {p_label:>15s} {a_label:<15s}   {toshow:<15s}")
        
    # the loop is now complete...
    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
        
        
# compare_labels(predicted_labels,actual_labels)

In [25]:
#
# let's try it out!
#

compare_labels(predicted_labels,actual_labels)

row 0    |  1.0  2.0  |   versicolor virginica   incorrect
row 1    |  1.0  1.0  |   versicolor versicolor   
row 2    |  1.0  2.0  |   versicolor virginica   incorrect
row 3    |  1.0  2.0  |   versicolor virginica   incorrect
row 4    |  1.0  1.0  |   versicolor versicolor   
row 5    |  1.0  2.0  |   versicolor virginica   incorrect
row 6    |  1.0  1.0  |   versicolor versicolor   
row 7    |  0.0  0.0  |   setosa setosa   
row 8    |  1.0  1.0  |   versicolor versicolor   
row 9    |  1.0  2.0  |   versicolor virginica   incorrect
row 10    |  1.0  1.0  |   versicolor versicolor   
row 11    |  1.0  2.0  |   versicolor virginica   incorrect
row 12    |  0.0  0.0  |   setosa setosa   
row 13    |  1.0  2.0  |   versicolor virginica   incorrect
row 14    |  1.0  1.0  |   versicolor versicolor   
row 15    |  1.0  2.0  |   versicolor virginica   incorrect
row 16    |  1.0  2.0  |   versicolor virginica   incorrect
row 17    |  1.0  2.0  |   versicolor virginica   incorrect
row 18    

In [57]:
#
# ok!  We _could_ be finished -- except that we _guessed_ at the keighborhood size (we guessed a k of 71)
#      Perhaps we should _explore_ whether other neighborhood sizes might better reflect our data... (?)

#
# to do this, we use "cross validation":  we split the _TRAINING_ data up and try different values of k
#

from sklearn.model_selection import cross_val_score

#
# cross-validation splits the training set into two pieces:
#   + model-building and model-validation. We'll use "build" and "validate"
#
# Lab challenge:  [1] loop over all values of k (or all _odd_ values of k...)  
#                 [2] assign best_k to the best one (highest average CV accuracy)

for k in range(1,72):
    knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build knn_model with current value of k

    cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # 5 is the "# of splits" (5 -> 80/20)
    #print('The 5 cross-validation accuracies: ', cv_scores,"\n")
    av = cv_scores.mean()
    print(f'k: {k:2d} produces an average CV accuracy of ', av)

# assign best value of k to best_k
best_k = 7      # at the moment, by hand - should be programmatic

k:  1 produces an average CV accuracy of  0.9292490118577075
k:  2 produces an average CV accuracy of  0.9027667984189722
k:  3 produces an average CV accuracy of  0.9292490118577075
k:  4 produces an average CV accuracy of  0.9027667984189722
k:  5 produces an average CV accuracy of  0.9292490118577075
k:  6 produces an average CV accuracy of  0.9205533596837944
k:  7 produces an average CV accuracy of  0.9379446640316205
k:  8 produces an average CV accuracy of  0.9292490118577075
k:  9 produces an average CV accuracy of  0.9292490118577075
k: 10 produces an average CV accuracy of  0.9292490118577075
k: 11 produces an average CV accuracy of  0.9292490118577075
k: 12 produces an average CV accuracy of  0.9209486166007904
k: 13 produces an average CV accuracy of  0.9296442687747035
k: 14 produces an average CV accuracy of  0.9296442687747035
k: 15 produces an average CV accuracy of  0.9201581027667984
k: 16 produces an average CV accuracy of  0.9205533596837944
k: 17 produces an averag

In [58]:
print(f"k = {best_k}   yields the highest average CV accuracy.")  # print the best one

k = 7   yields the highest average CV accuracy.


In [59]:
# Now, we re-create and re-run the  "Model-building and -training Cell"
#
# Now, using best_k instead of the original, randomly-guessed value    How does it do?!

from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k

# we train the model (one line!)
knn_model.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a knn classifier with k =", k)  

Created and trained a knn classifier with k = 71


In [60]:
# And, we re-create and re-run the  "Model-testing Cell"
#
# Now, using best_k instead of the original, randomly-guessed value    How does it do?!

# Now, run our test set!
predicted_labels = knn_model.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)

# and, we'll print our nicer table...
compare_labels(predicted_labels,actual_labels)

Predicted labels: [2. 1. 2. 2. 1. 2. 1. 0. 1. 2. 1. 1. 0. 2. 1. 2. 2. 2. 2. 1. 0. 2. 1. 2.
 1. 0. 2. 0.]
Actual labels: [2. 1. 2. 2. 1. 2. 1. 0. 1. 2. 1. 2. 0. 2. 1. 2. 2. 2. 2. 1. 0. 2. 1. 2.
 1. 0. 2. 0.]
row 0    |  2.0  2.0  |   virginica virginica   
row 1    |  1.0  1.0  |   versicolor versicolor   
row 2    |  2.0  2.0  |   virginica virginica   
row 3    |  2.0  2.0  |   virginica virginica   
row 4    |  1.0  1.0  |   versicolor versicolor   
row 5    |  2.0  2.0  |   virginica virginica   
row 6    |  1.0  1.0  |   versicolor versicolor   
row 7    |  0.0  0.0  |   setosa setosa   
row 8    |  1.0  1.0  |   versicolor versicolor   
row 9    |  2.0  2.0  |   virginica virginica   
row 10    |  1.0  1.0  |   versicolor versicolor   
row 11    |  1.0  2.0  |   versicolor virginica   incorrect
row 12    |  0.0  0.0  |   setosa setosa   
row 13    |  2.0  2.0  |   virginica virginica   
row 14    |  1.0  1.0  |   versicolor versicolor   
row 15    |  2.0  2.0  |   virginica virgin

In [61]:
#
# Plus, if new data arrives, you have a model with which to make predictions!
#
# here is a function for running new data (new flowers):
#
def predict_new_data(flower_data, knn_model):
    """ allows the user to enter values, from file or by hand, and then predict 
        the label using the knn_model passed in as input
    """
    # convert flower_data to a numpy array of float64 type (in case it's not already)
    flower_data = np.asarray(flower_data)
    flower_data.astype('float64')
    # how many dimensions?
    shape = flower_data.shape
    if len(shape) == 1:  # only one flower in one dimension ([a,b,c,d]) We need [[a,b,c,d]]
        flower_data = np.asarray( [flower_data] )  # need to wrap in extra square brackets!
        
    # print(flower_data.shape)
    NUM_ROWS, NUM_COLS = flower_data.shape   # get number of rows and number of cols

    # make the predictions
    predictions = knn_model.predict(flower_data)
    
    print()
    
    # print results
    for i in range(NUM_ROWS):
        flower = flower_data[i]
        predicted_label_as_number = predictions[i]
        predicted_label = NUM_TO_SPECIES[predicted_label_as_number]  # convert (back) to string!
        print(f"For {flower} the model predicts...   {predicted_label}")
        
    return predictions  # in case they're needed

print("predict_new_data defined.")

predict_new_data defined.


In [62]:
#
# test it out - with our own, typed data...
#

flower_data = [[ 5.4, 3.4, 1.5, 0.4]]   # change as you see fit!

predictions = predict_new_data( flower_data, knn_model )


For [5.4 3.4 1.5 0.4] the model predicts...   setosa


In [44]:
#
# try it yourself -- perhaps using the unknown data (printed here)
#

print("Unknown (unlabeled) data:\n")
print(X_unknown)
print("Their labels:", y_unknown)  # all unknown!

Unknown (unlabeled) data:

[[5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [5.7 2.9 4.2 1.3]
 [4.8 3.1 1.6 0.2]]
Their labels: [-1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [ ]:
#
# Be sure your results from trying this on the unknown data are here - or above!
#

In [ ]:
#
# That's it!  Welcome to the world of ML workflows!!    
#
#             Prediction: we'll be back for more ML! 
#